apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: broker-source
  labels:
    app: broker-source
    app.kubernetes.io/component: broker-source
    app.kubernetes.io/instance: broker-source
    app.kubernetes.io/name: broker-source
    app.kubernetes.io/part-of: broker-demo
spec:
  bootstrapServers:
    - 'my-cluster-kafka-bootstrap.amq-streams.svc:9092'
  consumerGroup: knative-broker-group
  consumers: 1
  initialOffset: latest
  net:
    sasl:
      password: {}
      type: {}
      user: {}
    tls:
      caCert: {}
      cert: {}
      key: {}
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker-demo
      namespace: eventing-demo
  topics:
    - eventing.broker.demo