= knative-demo

== Demo installation

=== Parameters

[options="header"]
|=======================
| Parameter | Example Value                                      | Definition
| token     | sha256~vFanQbthlPKfsaldJT3bdLXIyEkd7ypO_XPygY1DNtQ | access token for a user with cluster-admin privileges
| server    | https://api.mycluster.domain.com:6443              | OpenShift cluster API URL
|=======================

===  How to run the playbook

----
ansible-playbook -e token=${token} -e server=${server} playbook.yml
----


== Old Script
=== Basic Serving:

    kn service create hello-knative --image="quay.io/naveenkendyala/quarkus-demo-quarkusjvm-hello:v1"

    kn service list

    export URL=$(kn service list | tail -1 | awk '{print $2}')/api/hello

    hey -c 50 -z 10s $URL

    kn service update hello-knative --concurrency-limit=10

    hey -c 50 -z 10s $URL

    oc get kpa

=== Blue/Green Deployments

    kn service create example-svc \
    --image quay.io/redhattraining/do244-serving-manage \
    --revision-name example-svc-revision-1-blue \
    --env TARGET="Revision Blue" -n serving-demo

    export URL=$(kn service list | tail -1 | awk '{print $2}')

    curl $URL

    while true
    do
    curl $URL 
    sleep 1
    done

    kn service update example-svc \
    --revision-name example-svc-revision-2-green \
    --env TARGET="Revision Green"

=== Traffic Splitting

    kn service update example-svc --traffic example-svc-revision-1-blue=100

    kn service update example-svc \
    --traffic example-svc-revision-1-blue=80 \
    --traffic example-svc-revision-2-green=20

Show Topology for traffic splits in developer perspective:

* Click and change


=== Eventing

    oc project eventing-demo

    kn service create event-display1 \
        --image quay.io/openshift-knative/knative-eventing-sources-event-display:latest \
        --scale-window 10s

Ping Source, API Source, Kafka Source    

    kn source ping create test-ping-source \
        --schedule "*/1 * * * *" \
        --data '{"message": "Welcome to Knative Eventing!"}' \
        --sink ksvc:event-display1

Eventing:

Create a new project for kafka cluster

    oc project amq-streams

Create the cluster

    oc create -n amq-streams -f kafka-cluster.yaml

Create a new project for the demo

    oc project eventing-demo

    kn service create event-display1 \
        --image quay.io/openshift-knative/knative-eventing-sources-event-display:latest \
        --scale-window 10s

    kn source ping create test-ping-source \
        --schedule "*/1 * * * *" \
        --data '{"message": "Welcome to Knative Eventing!"}' \
        --sink ksvc:event-display1

Please refer to Eventing Demo Directory for Deep dive with Channel and Broker Demo of eventing

=== Functions Demo 

----
oc login

oc project functions-demo

git clone https://github.com/GuilhermeCamposo/demo_quarkus-function.git

cd demo_quarkus-fuction

kn func deploy --remote
----


=== Knative with Keda :

Please refer Keda-Demo directory and follow instructions.

Prerequisite: 
* Install Custom Metrics Autoscaler Operator
