apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  annotations:
    messaging.knative.dev/subscribable: v1
    openshift.io/generated-by: OpenShiftWebConsole
  name: kafka-channel
  finalizers:
    - kafkachannels.messaging.knative.dev
  labels:
    app: kafka-channel
    app.kubernetes.io/component: kafka-channel
    app.kubernetes.io/instance: kafka-channel
    app.kubernetes.io/name: kafka-channel
    app.kubernetes.io/part-of: channel-demo
spec:
  numPartitions: 1
  replicationFactor: 3
  retentionDuration: PT168H
