apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription-1
  generation: 1
  finalizers:
    - subscriptions.messaging.knative.dev
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display-01
      namespace: eventing-demo