apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source
  labels:
    app: ping-source
    app.kubernetes.io/component: ping-source
    app.kubernetes.io/instance: ping-source
    app.kubernetes.io/name: ping-source
    app.kubernetes.io/part-of: broker-demo
spec:
  data: '{"kafkaheadersubject": "invoice"}'
  schedule: '*/1 * * * *'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker-demo