- name: Evaluate Namespace eventing-demo
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: eventing-demo
    state: present

- name: Evaluate Topics
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    resource_definition: "{{ lookup('file', item) }}"
    namespace: amq-streams
  register: _serving
  retries: 1
  delay: 10
  until: not _serving.failed
  loop:
    - 3-topic-channel.yml

- name: Log in as super user with token on OpenShift 4
  ansible.builtin.command: "oc login --token={{ token }} --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
  when:
    - token is defined
    - token is not none
    - token|trim() != ""
  ignore_errors: false
  register: my_output
  changed_when: my_output.rc != 0

- name: Create Services
  ansible.builtin.command: |
    kn service create {{ item }} --image quay.io/openshift-knative/knative-eventing-sources-event-display
    --label app.kubernetes.io/part-of=channel-demo -n eventing-demo
  loop:
    - event-display-01
    - event-display-02
    - event-display-03
  register: my_output
  changed_when: my_output.rc != 0

- name: Evaluate Manifests
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    resource_definition: "{{ lookup('file', item) }}"
    namespace: eventing-demo
  register: _serving
  retries: 1
  delay: 10
  until: not _serving.failed
  loop:
    - 4-kafka-channel.yml
    - 5.1-subscription-1.yaml
    - 5.2-subscription-2.yaml
    - 5.3-subscription-3.yaml
    - 6-kafka-source-channel.yaml
